apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: auxiliary-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - auxiliary-service
  selector:
    matchLabels:
      app: auxiliary-service
  podMetricsEndpoints:
    - path: /metrics
      port: http
      interval: 15s
