apiVersion: v1
kind: Service
metadata:
  name: auxiliary-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: auxiliary-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}