image:
  repository: 905317844123.dkr.ecr.eu-west-1.amazonaws.com/main-api
  tag: "latest"
replicaCount: 1
service:
  port: 8000
version: "latest"
auxiliaryServiceUrl: "http://auxiliary-service.{{ .Release.Namespace }}.svc.cluster.local:8001"
imagePullSecrets:
  - name: regcred