image:
  tag: "83bc9705b2097b620bf8a099473421a1d714c4c0" # Will be updated to github.sha
replicaCount: 1
version: "83bc9705b2097b620bf8a099473421a1d714c4c0" # Will be updated to github.sha
auxiliaryServiceUrl: "http://auxiliary-service.dev.svc.cluster.local:8001"
