image:
  tag: "5984cbd908ae59a73a98d3cbc3f319732b9c98af" # Will be updated to github.sha by the pipeline
replicaCount: 1
version: "5984cbd908ae59a73a98d3cbc3f319732b9c98af" # Will be updated to github.sha
