image:
  tag: "5b2adf1a292c6108f7703f6e22b923db6a62b0d3" # Will be updated to github.sha by the pipeline
replicaCount: 1
version: "5b2adf1a292c6108f7703f6e22b923db6a62b0d3" # Will be updated to github.sha
