server:
  service:
    type: NodePort
    nodePortHttp: 30080 # expose the UI on http://NODE-IP:30080
    nodePortHttps: 30443
configs:
  params:
    "server.insecure": "true"  # skip TLS locally (UI served over plain HTTP)

repoServer:
  service:
    metricsPort: 8081
  metrics:
    enabled: true
    port: 8081

controller:
  config:
    configManagementPlugins:
      - name: kustomize
        generate:
          # call the CLI kustomize under the hood
          command: ["kustomize", "build"]
          args: ["--load-restrictor=none", "{{ .path }}"]