apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-service
  namespace: auxiliary-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auxiliary-service
  template:
    metadata:
      labels:
        app: auxiliary-service
    spec:
      containers:
        - name: auxiliary-service
          image: 905317844123.dkr.ecr.eu-west-1.amazonaws.com/auxiliary-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: SERVICE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: service-versions
                  key: auxiliary-service-version
      imagePullSecrets:
          - name: regcred