apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-service
  namespace: auxiliary-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auxiliary-service
  template:
    metadata:
      labels:
        app: auxiliary-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: auxiliary-service
          image: 905317844123.dkr.ecr.eu-west-1.amazonaws.com/auxiliary-service:a135f7579eef8787fbac5110a8a9611607f8837f
          ports:
            - name: http
              containerPort: 8001
          env:
            - name: SERVICE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: service-versions
                  key: auxiliary-service-version
            - name: AWS_ACCESS_KEY_ID 
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
      imagePullSecrets:
          - name: regcred