apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: main-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}