name: CI/CD Pipeline
on:
  push:
    branches: [main]
permissions:    
  id-token: write   # This is required for receiving the JWT   
  contents: write    # This is required for actions/checkout 
jobs:
  # validate-terraform:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.7.4
  #     - name: Terraform Init
  #       run: |
  #         cd terraform
  #         terraform init
  #     - name: Terraform Validate
  #       run: |
  #         cd terraform
  #         terraform validate
  build-and-push:
    runs-on: ubuntu-latest
    # needs: validate-terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::905317844123:role/kantox-challenge-github-actions-dev
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Main API
        run: |
          echo "Building Main API image..."
          docker build -t ${{ steps.login-ecr.outputs.registry }}/main-api:${{ github.sha }} ./main-api
          echo "Pushing Main API image..."
          docker push ${{ steps.login-ecr.outputs.registry }}/main-api:${{ github.sha }}
      - name: Build and Push Auxiliary Service
        run: |
          echo "Building Auxiliary Service image..."
          docker build -t ${{ steps.login-ecr.outputs.registry }}/auxiliary-service:${{ github.sha }} ./auxiliary-service
          echo "Pushing Auxiliary Service image..."
          docker push ${{ steps.login-ecr.outputs.registry }}/auxiliary-service:${{ github.sha }}
      - name: Update Kubernetes Manifests
        run: |
          echo "Updating Kubernetes manifests..."
          sed -i "s|image:.*main-api:.*|image: ${{ steps.login-ecr.outputs.registry }}/main-api:${{ github.sha }}|" base/deployments/main-api-deployment.yaml
          sed -i "s|image:.*auxiliary-service:.*|image: ${{ steps.login-ecr.outputs.registry }}/auxiliary-service:${{ github.sha }}|" base/deployments/auxiliary-service-deployment.yaml
          sed -i "s|main-api-version:.*|main-api-version: ${{ github.sha }}|" base/config/configmap-main.yaml
          sed -i "s|auxiliary-service-version:.*|auxiliary-service-version: ${{ github.sha }}|" base/config/configmap-aux.yaml
      - name: Commit and Push Changes
        run: |
          echo "Committing updated manifests..."
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add base/
          git commit -m "Update image tags and ConfigMap for commit ${{ github.sha }}" || echo "No changes to commit"
          git push